version: 2
jobs:
  build:
    working_directory: ~/svc
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/svc
    steps:
      - checkout
      - run: npm install
      - deploy:
          name: Deploy to npm
          command: npm run semantic-release
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
